# [P1] NumPy: Array Creation & Printing

**Generated:** 2025-09-20

> Tip: Run cells top → bottom. Keep notes in the 'Your notes' section.


## Objectives
- Fill these in after you finish the lesson.
- Example: understand shapes/dtypes; practice slicing; compute simple finance metrics.


## Setup

In [2]:
import numpy as np
np.__version__

'2.0.1'

## 1) Creation functions
- `np.array`, `np.zeros`, `np.ones`, `np.full`
- `np.arange` vs `np.linspace` (floats caution)
- `np.random` basics


In [ ]:
a = np.zeros((3,3))
b = np.ones((2,4))
c = np.full((2,2), 7.5)
d = np.arange(10, 30, 5)         # step
e = np.linspace(0, 1, 6)         # count
generator = np.random.default_rng(42)
f = generator.normal(loc=0, scale=1, size=10)

a, b, c, d, e, f[:5]

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[7.5, 7.5],
        [7.5, 7.5]]),
 array([10, 15, 20, 25]),
 array([0. , 0.2, 0.4, 0.6, 0.8, 1. ]),
 array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519]))

## 2) Printing neatly
- Slice head/tail, set print options, round for readability.


In [4]:
np.set_printoptions(precision=3, suppress=True)
large = rng.normal(size=(5,5))
print(large)

[[ 0.879  0.778  0.066  1.127  0.468]
 [-0.859  0.369 -0.959  0.878 -0.05 ]
 [-0.185 -0.681  1.223 -0.155 -0.428]
 [-0.352  0.532  0.365  0.413  0.431]
 [ 2.142 -0.406 -0.512 -0.814  0.616]]


## Exercise
Simulate 10 random daily returns (mean 0.1%, std 1%). Print first 5.


In [10]:
rets = rng.normal(loc=0.001, scale=0.01, size=10)
print(rets[:5])
print(rets)

[ 0.006 -0.004  0.001  0.006  0.005]
[ 0.006 -0.004  0.001  0.006  0.005  0.008  0.    -0.003  0.    -0.016]


## Your notes