# [P1] NumPy: Basic Operations

**Generated:** 2025-09-20

> Tip: Run cells top → bottom. Keep notes in the 'Your notes' section.


## Objectives
- Fill these in after you finish the lesson.
- Example: understand shapes/dtypes; practice slicing; compute simple finance metrics.


## Setup

In [1]:
import numpy as np
np.__version__

'2.0.1'

## 1) Elementwise vs matrix ops
- `+ - * /` are elementwise
- `@` is matrix multiplication (dot product)

In [2]:
x = np.array([1,2,3], dtype=float)
y = np.array([0.1, 0.2, 0.3])
print('elementwise * :', x*y)
print('dot product x@y :', x @ y)  # 1*0.1 + 2*0.2 + 3*0.3

elementwise * : [0.1 0.4 0.9]
dot product x@y : 1.4


## 2) Reductions & stats
- `np.mean`, `np.std`, `np.sum`, `np.min/max`


In [4]:
m = np.arange(1,10).reshape(3,3)
print('matrix:\n', m)
print('mean:', m.mean(), 'row means:', m.mean(axis=1), 'col means:', m.mean(axis=0))

matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
mean: 5.0 row means: [2. 5. 8.] col means: [4. 5. 6.]


## Finance example
Compute portfolio return from weights and asset returns.


In [5]:
weights = np.array([0.6, 0.4])
returns = np.array([0.02, -0.01])
portfolio_ret = weights @ returns
portfolio_ret

np.float64(0.008)

## Exercise
Given daily returns for 3 assets and weights, compute daily portfolio returns for 5 days.


In [6]:
R = np.array([[0.01, -0.02, 0.015],
              [0.005, 0.01, -0.03],
              [0.002, 0.003, 0.0],
              [0.01, 0.0, -0.005],
              [-0.002, 0.004, 0.006]])
w = np.array([0.5, 0.3, 0.2]) 
daily_port = R @ w
daily_port

array([ 0.002 , -0.0005,  0.0019,  0.004 ,  0.0014])

## Your notes