# [P1] NumPy: Indexing & Slicing

**Generated:** 2025-09-20

> Tip: Run cells top → bottom. Keep notes in the 'Your notes' section.


## Objectives
- Fill these in after you finish the lesson.
- Example: understand shapes/dtypes; practice slicing; compute simple finance metrics.


## Setup

In [1]:
import numpy as np
np.__version__

'2.0.1'

## 1) Basics
- Scalar index, slices, step, negative indices.

In [6]:
arr = np.arange(10)
print(arr)
arr[0], arr[1:5], arr[-3:]

[0 1 2 3 4 5 6 7 8 9]


(np.int64(0), array([1, 2, 3, 4]), array([7, 8, 9]))

## 2) 2D indexing
- Row/col selection, ranges, ellipsis


In [7]:
M = np.arange(1,13).reshape(3,4)
print(M)
row1 = M[0, :]
col2 = M[:, 1]
block = M[0:2, 1:3]
row1, col2, block

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(array([1, 2, 3, 4]),
 array([ 2,  6, 10]),
 array([[2, 3],
        [6, 7]]))

## 3) Boolean masks
Filter by condition.


In [8]:
rng = np.random.default_rng(0)
rets = rng.normal(0, 0.01, size=10)
print('returns:', rets)
positive = rets[rets > 0]
positive

returns: [ 0.0012573  -0.00132105  0.00640423  0.001049   -0.00535669  0.00361595
  0.01304     0.00947081 -0.00703735 -0.01265421]


array([0.0012573 , 0.00640423, 0.001049  , 0.00361595, 0.01304   ,
       0.00947081])

## Exercise
From a 2D array of daily returns (days×assets), select days where asset 0 > 0 and asset 1 < 0.


In [ ]:
R = rng.normal(0, 0.01, size=(8,3))
mask = (R[:,0] > 0) & (R[:,1] < 0)
R[mask]

## Your notes