# [P1] NumPy: Shape & Reshape

**Generated:** 2025-09-20

> Tip: Run cells top → bottom. Keep notes in the 'Your notes' section.


## Objectives
- Fill these in after you finish the lesson.
- Example: understand shapes/dtypes; practice slicing; compute simple finance metrics.


## Setup

In [1]:
import numpy as np
np.__version__

'2.0.1'

## 1) Shapes
- `.shape`, `.reshape`, `.ravel`, `.T` (transpose)

In [2]:
a = np.arange(12)
b = a.reshape(3,4)
c = b.T
print(a, b, c, sep='\n\n');
a.shape, b.shape, c.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


((12,), (3, 4), (4, 3))

## 2) Reshape calendar‑style
Reshape a 28‑day vector of returns into 4 weeks × 7 days.


In [3]:
rng = np.random.default_rng(1)
rets = rng.normal(0, 0.01, size=28)
weeks = rets.reshape(4,7)
weeks, weeks.shape

(array([[ 3.45584192e-03,  8.21618144e-03,  3.30437076e-03,
         -1.30315723e-02,  9.05355867e-03,  4.46374572e-03,
         -5.36953235e-03],
        [ 5.81118104e-03,  3.64572396e-03,  2.94132497e-03,
          2.84222413e-04,  5.46712987e-03, -7.36454087e-03,
         -1.62909948e-03],
        [-4.82119313e-03,  5.98846213e-03,  3.97221075e-04,
         -2.92456751e-03, -7.81908462e-03, -2.57192241e-03,
          8.14218052e-05],
        [-2.75602905e-03,  1.29406381e-02,  1.00672432e-02,
         -2.71116248e-02, -1.88901325e-02, -1.74772092e-03,
         -4.22190412e-03]]),
 (4, 7))

## Exercise
Given 60 trading‑day returns, reshape into 12 weeks of 5 days and compute weekly mean.


In [4]:
rets60 = rng.normal(0, 0.01, size=60)
weeks = rets60.reshape(12,5)
weekly_mean = weeks.mean(axis=1)
weekly_mean

array([ 0.00211836,  0.00238091, -0.00341229, -0.00283649,  0.00343837,
        0.00040067, -0.00443589, -0.00075903, -0.00255619,  0.00014908,
       -0.00243546, -0.0005458 ])

## Your notes