# [P1] NumPy: Broadcasting

**Generated:** 2025-09-20

> Tip: Run cells top → bottom. Keep notes in the 'Your notes' section.


## Objectives
- Fill these in after you finish the lesson.
- Example: understand shapes/dtypes; practice slicing; compute simple finance metrics.


## Setup

In [1]:
import numpy as np
np.__version__

'2.0.1'

## 1) Rules
- Align shapes from the right; length‑1 dims can expand.


In [2]:
prices = np.array([[100., 102., 101.],
                  [98., 99., 100.]])
weights = np.array([0.6, 0.4, 0.0])  # broadcast across rows
weighted = prices * weights
weighted, weighted.sum(axis=1)

(array([[60. , 40.8,  0. ],
        [58.8, 39.6,  0. ]]),
 array([100.8,  98.4]))

## 2) Add column vector to all rows


In [3]:
R = np.array([[0.01, -0.02, 0.015],
              [0.005, 0.01, -0.03]])
bias = np.array([[0.001],[ -0.002]])   # shape (2,1)
adj = R + bias
R.shape, bias.shape, adj

((2, 3),
 (2, 1),
 array([[ 0.011, -0.019,  0.016],
        [ 0.003,  0.008, -0.032]]))

## Exercise
Normalize each column of a (days×assets) matrix by subtracting column mean and dividing by column std (z‑score) using broadcasting.


In [4]:
generator = np.random.default_rng(2)
X = generator.normal(0,1,size=(6,3))
print(X)
mu = X.mean(axis=0)
sigma = X.std(axis=0)
Z = (X - mu) / sigma
Z.mean(axis=0), Z.std(axis=0)

[[ 0.18905338 -0.52274844 -0.41306354]
 [-2.44146738  1.79970738  1.14416587]
 [-0.32542284  0.77380659  0.28121067]
 [-0.55382284  0.97756745 -0.31055655]
 [-0.3288239  -0.79214676  0.45495807]
 [-0.09919805  0.54528871 -0.6071857 ]]


(array([ 9.25185854e-17, -1.38777878e-17, -3.70074342e-17]),
 array([1., 1., 1.]))

## Your notes