# 📘 NumPy Homework (7 Days) — With Self‑Checks

**Generated:** 2025-09-21

How to use:
- Solve each exercise in the **solution cell** provided.
- Then run the **Self‑check** cell below it. If it runs without errors → you passed.
- If an `AssertionError` appears, read the message and fix your work.

⚠️ Please use the **exact variable names** requested, so tests can find your answers.


## Day 1 — Arrays & Dtypes

Create a 2D NumPy array **`prices_int`** representing daily stock prices for **2 stocks over 5 days** (ints).

- Convert it to floats as **`prices`** and divide by 100 to express **pounds** instead of **pennies**.
- Print/check `.shape`, `.ndim`, `.dtype`, and `.itemsize`.

**Use these variable names:** see bold names in the prompt.

In [3]:
# Your solution here
import numpy as np
prices_int = np.array([[100, 101, 102, 103, 104],[105, 106, 107, 108, 109]]);
prices = prices_int.astype(float)/100;
print('prices:', prices);
print('| shape:', prices.shape, '| ndim:' ,prices.ndim, '| dtype:' , prices.dtype, '| itemsize:', prices.itemsize);


prices: [[1.   1.01 1.02 1.03 1.04]
 [1.05 1.06 1.07 1.08 1.09]]
| shape: (2, 5) | ndim: 2 | dtype: float64 | itemsize: 8


### Self‑check (run after your solution)

In [4]:
import numpy as np
assert 'prices_int' in globals(), "Define prices_int (2x5, integers)."
assert 'prices' in globals(), "Define prices as float version of prices_int/100."
assert isinstance(prices_int, np.ndarray), "prices_int must be a NumPy array."
assert prices_int.shape == (2,5), f"prices_int.shape should be (2,5), got {prices_int.shape}"
assert np.issubdtype(prices_int.dtype, np.integer), "prices_int must have integer dtype."
assert isinstance(prices, np.ndarray), "prices must be a NumPy array."
assert prices.shape == (2,5), "prices must match shape of prices_int."
assert np.issubdtype(prices.dtype, np.floating), "prices must have a float dtype."
np.testing.assert_allclose(prices, prices_int.astype(float)/100.0, err_msg="prices must equal prices_int/100 (float).")
print("✅ Day 1 passed!")

✅ Day 1 passed!


## Day 2 — Array Creation & Printing

Simulate **10 trading days** of daily returns for a single stock as **`returns10`**, using a normal distribution with mean = **0.1%** (0.001) and std = **1%** (0.01).

- Create **`days`** with `np.arange(10)`.
- Print the first 5 returns with 3 decimals (manually or via print options).

**Use these variable names:** see bold names in the prompt.

In [7]:
# Your solution here
import numpy as np
returns10 = np.random.default_rng(21).normal(loc=0.001, scale=0.01, size=10)
print('returns10:', returns10)
days = np.arange(10)
print('days:', days)
np.set_printoptions(precision=3, suppress=True)
print(returns10[:5])

returns10: [ 0.00458773  0.01610677 -0.01686331  0.01786614  0.00052683 -0.00699979
 -0.00702957 -0.00982817 -0.00123645  0.00933884]
days: [0 1 2 3 4 5 6 7 8 9]
[ 0.005  0.016 -0.017  0.018  0.001]


### Self‑check (run after your solution)

In [6]:
import numpy as np
assert 'returns10' in globals(), "Define returns10: array of 10 daily returns."
assert 'days' in globals(), "Define days = np.arange(10)."
assert isinstance(returns10, np.ndarray), "returns10 must be a NumPy array."
assert returns10.shape == (10,), "returns10 must be length 10."
assert np.isfinite(returns10).all(), "returns10 must be finite numbers."
assert isinstance(days, np.ndarray) and days.shape == (10,), "days must be np.arange(10)."
print("✅ Day 2 passed!")

✅ Day 2 passed!


## Day 3 — Basic Operations

Given portfolio **`weights = np.array([0.5, 0.3, 0.2])`**:
- Create a 2D array **`R`** of daily returns for **3 assets across 4 days** (shape **(4,3)**).
- Compute **`portfolio_daily` = R @ weights** (shape **(4,)**).

**Use these variable names:** see bold names in the prompt.

In [ ]:
# Your solution here
import numpy as np
weights = np.array([0.5, 0.3, 0.2])
R = np.array([[0.01, 0.02, 0.015], [0.005, 0.025, 0.02], [-0.01, 0.015, 0.03], [0.02, -0.005, 0.01]])
print(R.shape)
portfolio_daily = R.dot(weights)
print('portfolio_daily:', portfolio_daily)


(4, 3)
portfolio_daily: [0.014 0.014 0.005 0.011]


### Self‑check (run after your solution)

In [ ]:
import numpy as np
assert 'weights' in globals(), "Define weights = np.array([0.5, 0.3, 0.2])."
assert np.allclose(weights, np.array([0.5,0.3,0.2])), "weights must be [0.5, 0.3, 0.2]."
assert 'R' in globals(), "Define R with shape (4,3)."
assert isinstance(R, np.ndarray) and R.shape == (4,3), "R must be a (4,3) NumPy array."
assert 'portfolio_daily' in globals(), "Compute portfolio_daily = R @ weights."
assert isinstance(portfolio_daily, np.ndarray) and portfolio_daily.shape == (4,), "portfolio_daily must be length 4."
print("✅ Day 3 passed!")

✅ Day 3 passed!


## Day 4 — Indexing & Slicing

Create a **5×3** matrix **`R5`** of simulated daily returns.
- Select **`asset1`**: returns of asset index 0 for all 5 days → shape (5,).
- Select **`last2`**: last 2 days of all assets → shape (2,3).
- Select **`asset2_gt`**: all rows where asset index 1 > 0.01 → shape (?,3).

**Use these variable names:** see bold names in the prompt.

In [13]:
# Your solution here
import numpy as np
a = np.random.default_rng(21).normal(loc=0, scale=1, size=3)
b = np.ones(3)
c = np.full(3, 7.5)
d = np.arange(1, 4, 1)         # step
e = np.linspace(1, 4, 3) 

R5 = np.array([a, b, c, d, e])

print(R5)
print(R5.shape)

asset1 = R5[:,0]
print('asset1:', asset1)
last2 = R5[-2:,:]
print('last2:', last2)
asset2_gt = R5[R5[:,1]>0.01, :]
print('asset2_gt:', asset2_gt)


[[ 0.35877341  1.51067731 -1.78633124]
 [ 1.          1.          1.        ]
 [ 7.5         7.5         7.5       ]
 [ 1.          2.          3.        ]
 [ 1.          2.5         4.        ]]
(5, 3)
asset1: [0.35877341 1.         7.5        1.         1.        ]
last2: [[1.  2.  3. ]
 [1.  2.5 4. ]]
asset2_gt: [[ 0.35877341  1.51067731 -1.78633124]
 [ 1.          1.          1.        ]
 [ 7.5         7.5         7.5       ]
 [ 1.          2.          3.        ]
 [ 1.          2.5         4.        ]]


### Self‑check (run after your solution)

In [14]:
import numpy as np
assert 'R5' in globals(), "Define R5 with shape (5,3)."
assert isinstance(R5, np.ndarray) and R5.shape == (5,3), "R5 must be (5,3)."
assert 'asset1' in globals() and isinstance(asset1, np.ndarray) and asset1.shape == (5,), "asset1 must be R5[:,0] shape (5,)."
assert 'last2' in globals() and isinstance(last2, np.ndarray) and last2.shape == (2,3), "last2 must be last 2 rows, shape (2,3)."
assert 'asset2_gt' in globals() and isinstance(asset2_gt, np.ndarray) and asset2_gt.shape[1] == 3, "asset2_gt must have 3 columns."
print("✅ Day 4 passed!")

✅ Day 4 passed!


## Day 5 — Shape & Reshape

Simulate **20 daily returns** as **`rets20`**.
- Reshape to **`weeks`** with shape (4,5).
- Compute **`weekly_mean`** (shape (4,)) = mean across axis=1.

**Use these variable names:** see bold names in the prompt.

In [16]:
# Your solution here
import numpy as np
rets20 = np.random.default_rng(21).normal(loc=0, scale=1, size=20)
print('rets20:', rets20)
weeks = rets20.reshape(4,5)
print('weeks:\n', weeks)
weekly_mean = weeks.mean(axis=1)
print('weekly_mean:', weekly_mean)

rets20: [ 0.35877341  1.51067731 -1.78633124  1.68661351 -0.04731721 -0.79997858
 -0.80295672 -1.08281652 -0.22364536  0.83388418  0.58406373  0.63828602
 -1.69480839 -1.57096212  1.55380317  0.96888537  2.183214    1.20981583
 -1.02439134  1.28527245]
weeks:
 [[ 0.35877341  1.51067731 -1.78633124  1.68661351 -0.04731721]
 [-0.79997858 -0.80295672 -1.08281652 -0.22364536  0.83388418]
 [ 0.58406373  0.63828602 -1.69480839 -1.57096212  1.55380317]
 [ 0.96888537  2.183214    1.20981583 -1.02439134  1.28527245]]
weekly_mean: [ 0.34448316 -0.4151026  -0.09792352  0.92455926]


### Self‑check (run after your solution)

In [17]:
import numpy as np
assert 'rets20' in globals() and isinstance(rets20, np.ndarray) and rets20.shape == (20,), "rets20 must be length 20."
assert 'weeks' in globals() and isinstance(weeks, np.ndarray) and weeks.shape == (4,5), "weeks must be (4,5)."
assert 'weekly_mean' in globals() and isinstance(weekly_mean, np.ndarray) and weekly_mean.shape == (4,), "weekly_mean must be (4,)."
print("✅ Day 5 passed!")

✅ Day 5 passed!


## Day 6 — Broadcasting

Create a (4×3) price matrix **`prices43`**.
- Compute column means **`col_mean`** (shape (3,)).
- Normalize as **`norm = prices43 - col_mean`** using broadcasting.
- (Optional) Check that `norm.mean(axis=0)` is close to 0.

**Use these variable names:** see bold names in the prompt.

In [25]:
# Your solution here
import numpy as np
prices43 = np.random.default_rng(21).normal(loc=0, scale=1, size=12).reshape(4,3)
col_mean = prices43.mean(axis=0)
norm = prices43 - col_mean;
print('norm.mean(axis=0):\n', norm.mean(axis=0))
print(np.allclose(norm.mean(axis=0), 0))

norm.mean(axis=0):
 [-2.77555756e-17  5.55111512e-17 -5.55111512e-17]
True


### Self‑check (run after your solution)

In [26]:
import numpy as np
assert 'prices43' in globals() and isinstance(prices43, np.ndarray) and prices43.shape == (4,3), "prices43 must be (4,3)."
assert 'col_mean' in globals() and isinstance(col_mean, np.ndarray) and col_mean.shape == (3,), "col_mean must be (3,)."
assert 'norm' in globals() and isinstance(norm, np.ndarray) and norm.shape == (4,3), "norm must be (4,3)."
# Optional sanity check (tolerant)
assert np.all(np.isfinite(norm)), "norm must be finite."
print("✅ Day 6 passed!")

✅ Day 6 passed!


## Day 7 — 3D Finance Mini‑Project

Simulate a **(3×6×2)** array **`data`** = 3 stocks × 6 days × 2 features (Close, Volume).
- Extract volumes as **`volumes`** (shape (3,6)).
- Transpose to time‑major **`time_major`** with shape (6,3,2).
- Compute Close‑based daily returns **`rets`** (shape (3,5)).

**Use these variable names:** see bold names in the prompt.

In [ ]:
# Your solution here
import numpy as np


### Self‑check (run after your solution)

In [ ]:
import numpy as np
assert 'data' in globals() and isinstance(data, np.ndarray) and data.shape == (3,6,2), "data must be shape (3,6,2)."
assert 'volumes' in globals() and isinstance(volumes, np.ndarray) and volumes.shape == (3,6), "volumes must be (3,6)."
assert 'time_major' in globals() and isinstance(time_major, np.ndarray) and time_major.shape == (6,3,2), "time_major must be (6,3,2)."
assert 'rets' in globals() and isinstance(rets, np.ndarray) and rets.shape == (3,5), "rets must be (3,5)."
print("✅ Day 7 passed!")